version: 2
jobs:
  build:
    docker:
      - image: circleci/ubuntu-server
    steps:
      - run: apt-get update
      - run: apt-get -y install git build-essential
      - checkout
      - run: make test