version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - run: pacman -Syyu --noconfirm
      - run: pacman -S --noconfirm base-devel clang
      - checkout
      - run: make test