version: 2
jobs:
  build:
    docker:
      - image: circleci/ubuntu-server
    steps:
      - run: apt-get update
      - run: apt-get -y install git make clang-3.5 llvm
      - run: ln -s /usr/bin/clang++-3.5 /usr/bin/clang++
      - checkout
      - run: make test